### ISSUE TITLE
Steghide -e algorithm documentation 

### ISSUE THREAD

**Issue by Pandacat-sudoer** [StefanoDeVuono/steghide#17]
Can you add the supported encryption algorithm alias, I mean I try to use the exact same name from libmcrypt manual for the -e flag but can't be work

**Comment by Pandacat-sudoer** [comment]
Something like list of algorithm that can be used

**Comment by StefanoDeVuono** [comment]
Hello @Pandacat-sudoer. I don't know if you're still following this repo, but we've created an org StegHigh to maintain it. We've transferred the repository, but unfortunately we cannot transfer issues.

Please copy this issue to the [new repository](https://github.com/StegHigh/steghide/issues).

Alternatively, if you feel this is better as a topic of discussion, please post in [StegHigh discussions](https://github.com/orgs/StegHigh/discussions).

Thanks!
