### ISSUE TITLE
mv: não foi possível obter estado de 't-es.gmo': Arquivo ou diretório inexistente

### ISSUE THREAD

**Issue by anzormarkov** [StefanoDeVuono/steghide#2]
make[2]: Entering directory '/home/markov/hack/steghide/po'
cd .. \
  && CONFIG_FILES=po/Makefile.in CONFIG_HEADERS= \
       /bin/sh ./config.status
config.status: creating po/Makefile.in
config.status: WARNING:  'po/Makefile.in.in' seems to ignore the --datarootdir setting
config.status: executing depfiles commands
config.status: executing default-1 commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
rm -f es.gmo && : -c --statistics -o es.gmo es.po
mv: não foi possível obter estado de 't-es.gmo': Arquivo ou diretório inexistente
Makefile:207: recipe for target 'es.gmo' failed
make[2]: *** [es.gmo] Error 1
make[2]: Leaving directory '/home/markov/hack/steghide/po'
Makefile:259: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/markov/hack/steghide'
Makefile:190: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by StefanoDeVuono** [comment]
Hello @anzormarkov. I don't know if you're still following this repo, but we've created an org StegHigh to maintain it. We've transferred the repository, but unfortunately we cannot transfer issues.

Please copy this issue to the [new repository](https://github.com/StegHigh/steghide/issues).

Alternatively, if you feel this is better as a topic of discussion, please post in [StegHigh discussions](https://github.com/orgs/StegHigh/discussions).

Thanks/Obrigado!
