### ISSUE TITLE
Arbitrary file write

### ISSUE THREAD

**Issue by MyEyes** [StefanoDeVuono/steghide#5]
Steghide doesn't sanitize the output file, which allows arbitrary files to be written.
See https://firzen.de/git-rekt-2-steghide for details.

**Comment by StefanoDeVuono** [comment]
Hello @MyEyes. I don't know if you're still following this repo, but we've created an org StegHigh to maintain it. We've transferred the repository, but unfortunately we cannot transfer issues.

Please copy this issue to the [new repository](https://github.com/StegHigh/steghide/issues).

Alternatively, if you feel this is better as a topic of discussion, please post in [StegHigh discussions](https://github.com/orgs/StegHigh/discussions).

Thanks!
