### ISSUE TITLE
wav format is not supported

### ISSUE THREAD

**Issue by khalidalwalid** [StefanoDeVuono/steghide#6]
Hello, I have a problem when I want to embed .wav and actually also .au audio file format using steghide like this
![steghideproblem](https://user-images.githubusercontent.com/33023197/97957727-c64b3d00-1d79-11eb-802a-d5d8e4575cc4.png)

Any solutions?

**Comment by lazyfox77** [comment]
Hello,

The same error throw at me, and found that It is an error in the audio decoding format for the wav file, it must be a Microsoft PCM (the value is declared twice, at WavFile.h and WavFormatChunk.h, and declared as 1 and 0x0001 respectively), the file format must be something like this: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz (https://exiftool.org/TagNames/RIFF.html this page describes the RIFF metadata).

I managed to bypass the error generating a wav file from a mp3 with mpg123 without specifing the rate: mpg123 -w file.wav file.mp3.

I don't think this will be patched or add more formats, this project is dead from long time ago :(

**Comment by StefanoDeVuono** [comment]
Hello @khalidalwalid. I don't know if you're still following this repo, but we've created an org StegHigh to maintain it. We've transferred the repository, but unfortunately we cannot transfer issues.

Please copy this issue to the [new repository](https://github.com/StegHigh/steghide/issues).

Alternatively, if you feel this is better as a topic of discussion, please post in [StegHigh discussions](https://github.com/orgs/StegHigh/discussions).

Thanks!
